# Generated by Django 2.1.5 on 2019-02-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(max_length=20)),
                ('brandname', models.CharField(max_length=50)),
                ('img1', models.CharField(max_length=251)),
                ('productid1', models.CharField(max_length=10, null=True)),
                ('childcid1', models.CharField(max_length=20)),
                ('longname1', models.CharField(max_length=255)),
                ('price1', models.CharField(max_length=15)),
                ('marketprice1', models.CharField(max_length=15)),
                ('img2', models.CharField(max_length=251)),
                ('productid2', models.CharField(max_length=10, null=True)),
                ('childcid2', models.CharField(max_length=20)),
                ('longname2', models.CharField(max_length=255)),
                ('price2', models.CharField(max_length=15)),
                ('marketprice2', models.CharField(max_length=15)),
                ('img3', models.CharField(max_length=251)),
                ('productid3', models.CharField(max_length=10, null=True)),
                ('childcid3', models.CharField(max_length=20)),
                ('longname3', models.CharField(max_length=255)),
                ('price3', models.CharField(max_length=15)),
                ('marketprice3', models.CharField(max_length=15)),
            ],
        ),
    ]
