# Generated by Django 2.1.5 on 2019-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_mainshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainshow',
            name='img',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainshow',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainshow',
            name='trackid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
